LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY mux_4_2 IS
  PORT (
    A : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    B : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    S : IN STD_LOGIC;
    Z : OUT STD_LOGIC_VECTOR(1 DOWNTO 0)
  );
END mux_4_2;

ARCHITECTURE Behavioral OF mux_4_2 IS
BEGIN
  Z <= A WHEN S = '0' ELSE B;
END Behavioral;
